version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/types"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "npm"
    directory: "/packages/fetch"
    schedule:
      interval: "daily"
  
    - package-ecosystem: "npm"
    directory: "/packages/prompt"
    schedule:
      interval: "daily"
  
    - package-ecosystem: "npm"
    directory: "/packages/logger"
    schedule:
      interval: "daily"
  
    - package-ecosystem: "npm"
    directory: "/packages/discord-client"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
