name: Discord Client

on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - uses: c-hive/gha-npm-cache@v1
      - name: Install Dependencies
        run: |
          npm i
          npm i -ws
      - name: Build the Packages
        run: npm run build -ws
      - name: Publish Packages
        run: npm publish -w @infinite-fansub/discord-client --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM}}