name: Tests & Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build application on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - run: npm i
      - run: npm i -ws
      - run: npm run test -ws
      - run: npm run build -ws